run:
  timeout: 5m
  go: '1.20'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - appendAssign
  goimports:
    local-prefixes: github.com/chicogong/flow-tts

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
